### PR TITLE
Device

### PR DESCRIPTION
**Pull request by chudisoft**
**Project requirements**

    Remove current_user method in ApplicationController, devise will provide us with one.
    [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
        Can register a new user.
        User logs in with a combination of email and password.
        Hashed password should be stored in the database.
        Ask for confirmation of email.
        Can reset password.
   [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

### CODE REVIEW

**Comment by chudisoft** [comment]
To setup the proper environment for test, run:
rails db:reset
rails db:test:prepare
rails db:seed --trace
rails db:migrate

**Comment by prolajumokeoni** [comment]
Hi @chudisoft, this is a pair programming project I can't see meaningful commits from your current partner are you working solo this week? if not, you have to have commits from your partner on this pull request 👍🏿

**Comment by chudisoft** [comment]
> Hi @chudisoft, this is a pair programming project I can't see meaningful commits from your current partner are you working solo this week? if not, you have to have commits from your partner on this pull request 👍🏿

Yes my partner absconded.

**Comment by prolajumokeoni** [comment]
Hi @chudisoft, did you get approval from student success to work solo, if yes kindly add a screenshot 👍🏿

**Comment by chudisoft** [comment]
> Hi @chudisoft, did you get approval from student success to work solo, if yes kindly add a screenshot 👍🏿

No. It's weekend already.

**Comment by prolajumokeoni** [comment]
I might not be able to review your project unless you get approval to work solo, you can still reach out to Student Success hopefully you get a response, please always reach out to Student Success early so that you can be unpaired 👍🏿

**Comment by chudisoft** [comment]
> I might not be able to review your project unless you get approval to work solo, you can still reach out to Student Success hopefully you get a response, please always reach out to Student Success early so that you can be unpaired 👍🏿

Don't waste time. Kindly free the project. You can mark as invalid. Thanks

**Comment by prolajumokeoni** [comment]
Hi @chudisoft 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have commit from your current partner 👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
